import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
	Box,
	createTheme,
	Grid,
	Stack,
	ThemeProvider,
	Typography,
} from "@mui/material";
import Navbar from "../components/Navbar";
import SideBar from "../components/SideBar";
import Layout from "../components/Layout";
import Left from "../components/Index/Left";
import Right from "../components/Index/Right";
import Login from "./login";
import { useFetchUser, useUser } from "../components/lib/authContext";

export default function Home() {
	const { user, loading } = useFetchUser();
	return (
		<>
			<Head>
				<title>Frankcon ERP Design System</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			{/* <Grid container>
				<Grid item md={3}>
					<SideBar />
				</Grid>
				<Grid item md={9}>
					<Navbar />
					<Stack direction="row" gap="46px">
						<Left />
						<Right />
					</Stack>
				</Grid>
			</Grid> */}
			{!loading && !user ? (
				<>
					<Login />
				</>
			) : (
				<Stack
					direction="row"
					justifyContent="space-between"
					bgcolor="#F6F6F6"
					height="100vh"
				>
					<SideBar />
					<Stack direction="column" width="80%" height="100vh">
						<Navbar />
						Dashboard
					</Stack>
				</Stack>
			)}
		</>
	);
}
